#####
# there are some popular default convention style that I will list below
# SpaceBeforeBlockBraces:
#   EnforcedStyle: space
#
# Layout/SpaceInsideBlockBraces:
#   EnforcedStyle: space
#
###

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'

  TargetRubyVersion: 2.5

Lint/BooleanSymbol:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 115
  IgnoredPatterns: ['(\A|\s)#']
  Exclude:
    - 'features/**/*'
    - 'spec/**/*.rb'
    - 'dev-seeds/**/*'
    - 'lib/streams/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'Gemfile'

Layout/FirstParameterIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Exclude:
    - 'spec/**/*.rb'

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  Exclude:
    - 'spec/**/*.rb'

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*.rb'

Style/SymbolProc:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false
